name: build docker image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/jerchende/docker-jdk11-maven-nodejs:latest && docker push ghcr.io/jerchende/docker-jdk11-maven-nodejs:latest

